name: Terraform Check

on:
  pull_request:
    paths:
      - "**/*.tf"
      - "**/*.tfvars.example"
      - ".github/workflows/terraform-check.yml"
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.8
          terraform_wrapper: false
      - uses: terraform-linters/setup-tflint@v5
        with:
          tflint_version: v0.59.1
      - run: terraform fmt -check -recursive
      - run: terraform -chdir=bootstrap/backend init -backend=false -input=false
      - run: terraform -chdir=bootstrap/backend validate
      - run: terraform -chdir=environments/dev init -backend=false -input=false
      - run: terraform -chdir=environments/dev validate
      - run: terraform -chdir=environments/staging init -backend=false -input=false
      - run: terraform -chdir=environments/staging validate
      - run: terraform -chdir=environments/prod init -backend=false -input=false
      - run: terraform -chdir=environments/prod validate
      - run: terraform test
      - run: tflint --init
      - run: tflint --recursive
      - uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          quiet: true
          framework: terraform

